# Generated by Django 2.2.5 on 2021-07-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scjd_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpDistributionPieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
