# Generated by Django 2.2.5 on 2021-07-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scjd_data', '0002_epdistributionpiedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsWordMapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
