# Generated by Django 3.0.5 on 2021-07-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='filesmodel',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
