# Generated by Django 3.0.5 on 2021-07-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20210720_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='can_del',
            field=models.BooleanField(default=True),
        ),
    ]
