# Generated by Django 3.0.5 on 2021-09-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未命名图表', max_length=100)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('display', models.BooleanField(default=False)),
                ('removable', models.BooleanField(default=False)),
                ('x_coordinate', models.IntegerField(default=0)),
                ('y_coordinate', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=500)),
                ('height', models.IntegerField(default=500)),
            ],
            options={
                'db_table': 'chart_info',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('file_url', models.FileField(upload_to='uploads/')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='chart_data.Chart')),
            ],
            options={
                'db_table': 'file_history',
                'ordering': ['-chart', '-timestamp'],
            },
        ),
    ]
