# Generated by Django 3.0.5 on 2021-08-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filehistory',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
