# Generated by Django 3.0.5 on 2021-08-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data', '0003_auto_20210802_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filehistory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='filehistory',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
