# Generated by Django 3.0.5 on 2021-08-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data', '0004_auto_20210802_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(default='未命名图表', max_length=100),
        ),
    ]
