# Generated by Django 3.0.5 on 2021-08-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data', '0005_auto_20210803_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filehistory',
            options={'ordering': ['-chart', '-timestamp']},
        ),
    ]
