# Generated by Django 3.0.5 on 2021-08-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data', '0006_auto_20210803_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filehistory',
            old_name='json_url',
            new_name='file_url',
        ),
    ]
