# Generated by Django 3.0.5 on 2021-09-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data', '0007_auto_20210817_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
